
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { RouteObject } from "react-router-dom";




import About from "./pages/About.tsx";
import App from "./pages/App.tsx";
import BibleStudyPage from "./pages/BibleStudyPage.tsx";
import CalendarPage from "./pages/CalendarPage.tsx";
import EventManager from "./pages/EventManager.tsx";
import Events from "./pages/Events.tsx";
import FamilyMinistryPage from "./pages/FamilyMinistryPage.tsx";
import Give from "./pages/Give.tsx";
import Ministries from "./pages/Ministries.tsx";
import MusicMinistryPage from "./pages/MusicMinistryPage.tsx";
import OutreachMissionsMinistry from "./pages/OutreachMissionsMinistry.tsx";
import PrayerMinistryPage from "./pages/PrayerMinistryPage.tsx";
import SermonManager from "./pages/SermonManager.tsx";
import Sermons from "./pages/Sermons.tsx";
import WordOfGodMinistry from "./pages/WordOfGodMinistry.tsx";

export const userRoutes: RouteObject[] = [



	{ path: "/about", element: <About /> },
	{ path: "/", element: <App /> },
	{ path: "/bible-study-page", element: <BibleStudyPage /> },
	{ path: "/biblestudypage", element: <BibleStudyPage /> },
	{ path: "/calendar-page", element: <CalendarPage /> },
	{ path: "/calendarpage", element: <CalendarPage /> },
	{ path: "/event-manager", element: <EventManager /> },
	{ path: "/eventmanager", element: <EventManager /> },
	{ path: "/events", element: <Events /> },
	{ path: "/family-ministry-page", element: <FamilyMinistryPage /> },
	{ path: "/familyministrypage", element: <FamilyMinistryPage /> },
	{ path: "/give", element: <Give /> },
	{ path: "/ministries", element: <Ministries /> },
	{ path: "/music-ministry-page", element: <MusicMinistryPage /> },
	{ path: "/musicministrypage", element: <MusicMinistryPage /> },
	{ path: "/outreach-missions-ministry", element: <OutreachMissionsMinistry /> },
	{ path: "/outreachmissionsministry", element: <OutreachMissionsMinistry /> },
	{ path: "/prayer-ministry-page", element: <PrayerMinistryPage /> },
	{ path: "/prayerministrypage", element: <PrayerMinistryPage /> },
	{ path: "/sermon-manager", element: <SermonManager /> },
	{ path: "/sermonmanager", element: <SermonManager /> },
	{ path: "/sermons", element: <Sermons /> },
	{ path: "/word-of-god-ministry", element: <WordOfGodMinistry /> },
	{ path: "/wordofgodministry", element: <WordOfGodMinistry /> },

];
